const projects = [
  {
    id: 1,
    icon: '🌐',
    name: 'Portfolio',
    desc: 'Personal portfolio site with an embedded AI resume agent — machine-readable JSON for recruiting tools.',
    stack: ['HTML', 'CSS', 'JavaScript'],
    status: 'live',
    link: 'https://hemanthloq.github.io',
    difficulty: 'easy',
  },
  {
    id: 2,
    icon: '📄',
    name: 'PYQ Buddy',
    desc: 'Upload past exam PDFs and get RAG-powered analysis, topic breakdowns, and predicted questions.',
    stack: ['Python', 'FastAPI', 'ChromaDB', 'LangChain'],
    status: 'soon',
    link: null,
    difficulty: 'hard',
  },
  {
    id: 3,
    icon: '🧠',
    name: 'LocalMind',
    desc: 'Natural language to SQL query engine powered by Ollama — runs entirely on your machine.',
    stack: ['Python', 'Ollama', 'FastAPI', 'SQLite'],
    status: 'soon',
    link: null,
    difficulty: 'mid',
  },
  {
    id: 4,
    icon: '🎙️',
    name: 'MeetMind',
    desc: 'Record or upload meeting audio and get transcription, summaries, and action items automatically.',
    stack: ['Python', 'Whisper', 'FastAPI', 'React'],
    status: 'soon',
    link: null,
    difficulty: 'mid',
  },
  {
    id: 5,
    icon: '🔍',
    name: 'ResearchMind',
    desc: 'Autonomous web research agent that gathers, synthesises, and cites sources on any topic.',
    stack: ['LangGraph', 'Tavily', 'OpenAI', 'FastAPI'],
    status: 'soon',
    link: null,
    difficulty: 'hard',
  },
  {
    id: 6,
    icon: '👗',
    name: 'StyleSense',
    desc: 'Upload your outfit and get GPT-4 Vision feedback on style, fit, and occasion suitability.',
    stack: ['GPT-4V', 'React', 'FastAPI', 'Python'],
    status: 'soon',
    link: null,
    difficulty: 'mid',
  },
  {
    id: 7,
    icon: '🤖',
    name: 'Portfolio AI',
    desc: 'Embedded chatbot backed by RAG over my resume and projects — ask it anything about me.',
    stack: ['RAG', 'ChromaDB', 'React', 'FastAPI'],
    status: 'soon',
    link: null,
    difficulty: 'hard',
  },
];
